### ISSUE TITLE
Build fail

### ISSUE THREAD

**Issue by breeswish** [pingcap/go-ycsb#133]
```
fatal: unable to access 'https://git.apache.org/thrift.git/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to git.apache.org:443 
```

Suggest to apply a patch similar to https://github.com/kubernetes/minikube/issues/5245

**Comment by YangKeao** [comment]
Like googleapis/google-cloud-go-testing#27 . Updating cloud.google.com/go can simply fix this bug.

PR #134 has been submitted.
