### ISSUE TITLE
gorocksdb issue

### ISSUE THREAD

**Issue by softarts** [pingcap/go-ycsb#146]
![ycsb1](https://user-images.githubusercontent.com/3594521/73639381-36bc1500-46a7-11ea-9a52-bc7af159da6e.png)

looks the gorocksdb link broken?

**Comment by orhanhenrik** [comment]
Same issue here! Repo seems to have been deleted?

**Comment by zhouqiang-cl** [comment]
@softarts @orhanhenrik We will fix it soon
