### ISSUE TITLE
too many errors while compiling (make)

### ISSUE THREAD

**Issue by CES-dengzeyuan** [pingcap/go-ycsb#225]
go build -o bin/go-ycsb cmd/go-ycsb/*
# github.com/pingcap/go-ycsb/db/mysql
db/mysql/db.go:235:6: buf.WriteString undefined (type []byte has no field or method WriteString)
db/mysql/db.go:237:6: buf.WriteString undefined (type []byte has no field or method WriteString)
db/mysql/db.go:240:6: buf.WriteByte undefined (type []byte has no field or method WriteByte)
db/mysql/db.go:242:7: buf.WriteByte undefined (type []byte has no field or method WriteByte)
db/mysql/db.go:246:5: buf.WriteByte undefined (type []byte has no field or method WriteByte)
db/mysql/db.go:248:14: buf.String undefined (type []byte has no field or method String)
db/mysql/db.go:365:5: buf.WriteString undefined (type []byte has no field or method WriteString)
db/mysql/db.go:366:5: buf.WriteString undefined (type []byte has no field or method WriteString)
db/mysql/db.go:367:5: buf.WriteString undefined (type []byte has no field or method WriteString)
db/mysql/db.go:373:6: buf.WriteString undefined (type []byte has no field or method WriteString)
db/mysql/db.go:373:6: too many errors
make: *** [build] Error 2

**Comment by 94rain** [comment]
Hopefully #224 can fix this
