### ISSUE TITLE
make error : no new variables on left side of :=

### ISSUE THREAD

**Issue by apple-ouyang** [pingcap/go-ycsb#226]
I set this in my .zhsrc to avoid io time out
```sh
export GOPROXY=https://goproxy.io
```

Then I run the make, here is the output:
```sh
CGO_CXXFLAGS=" -std=c++11" go build -tags " rocksdb" -o bin/go-ycsb cmd/go-ycsb/*
# github.com/pingcap/go-ycsb/db/rocksdb
db/rocksdb/db.go:239:11: no new variables on left side of :=
Makefile:23: recipe for target 'build' failed
make: *** [build] Error 2
```

**Comment by apple-ouyang** [comment]
After I change the db/rocksdb/db.go:239
from 
```go
	buf, err := db.r.Encode(buf, m)
```
to
```go
	buf, err = db.r.Encode(buf, m)
```
the error is gone

**Comment by 94rain** [comment]
I cannot reproduce this on MacOS. (my go version is go1.18.2 darwin/amd64)

**Comment by apple-ouyang** [comment]
Here is my go version
```shell
$ go version
go version go1.18.2 linux/amd64
```
I have a global old go, go1.13.6 in /usr/local/bin.
So I download the latest new version of go and run 
```
tar -C ~/.local -xf go1.18.2.linux-amd64.tar.gz
```
and set 
```
export PATH=/home/wht/.local/go/bin:$PATH
export GOPROXY=https://goproxy.io
```
in .zshrc (I use zsh, you can set it in ~/.bashrc if you use bash)

**Comment by 94rain** [comment]
I just ran the following but still cannot reproduce the issue.
```shell
export GOPROXY=https://goproxy.io
go clean -modcache 
make
```

**Comment by apple-ouyang** [comment]
So maybe I shoud move the issue to rocksDB?
Please tell me where I can put the issue?

**Comment by 94rain** [comment]
Sorry I meant the issue only occurs with a local rocksdb installation. I am just trying to reproduce it. 

I think foundationdb also has this issue.
https://github.com/pingcap/go-ycsb/blob/03896359b993e55b0812431ab0a5228647007a62/db/foundationdb/db.go#L160

**Comment by apple-ouyang** [comment]
Thank you!
Hope you can figure it out.
