### ISSUE TITLE
go-ycsb scylla insert failed,  error info not enough to resolve

### ISSUE THREAD

**Issue by qiuxinyidian** [pingcap/go-ycsb#266]
`[root@node1 ~]#  ./go-ycsb load scylla -P workloads/workloada -p scylla.username=cassandra -p scylla.password=cassandra -p cassandra.cluster=192.168.167.67:9042,192.168.167.68:9042,192.168.167.122:9042  -p  cassandra.connections=3 -p threadcount=96 -p recordcount=100000000 -p insertstart=0 -p insertcount=33000000 
nohup: ignoring input
Using request distribution 'uniform' a keyrange of [0 32999999]
***************** properties *****************
"cassandra.connections"="3"
"requestdistribution"="uniform"
"scylla.password"="cassandra"
"command"="load"
"cassandra.cluster"="192.168.167.67:9042,192.168.167.68:9042,192.168.167.122:9042"
"operationcount"="100000"
"threadcount"="96"
"workload"="core"
"readallfields"="true"
"dotransactions"="false"
"readproportion"="0.5"
"insertstart"="0"
"scanproportion"="0"
"recordcount"="100000000"
"insertcount"="33000000"
"updateproportion"="0.5"
"insertproportion"="0"
"scylla.username"="cassandra"
**********************************************
INSERT - Takes(s): 10.0, Count: 418379, OPS: 41850.3, Avg(us): 2167, Min(us): 465, Max(us): 19231, 99th(us): 8687, 99.9th(us): 9879, 99.99th(us): 11767
INSERT - Takes(s): 20.0, Count: 837248, OPS: 41869.7, Avg(us): 2166, Min(us): 452, Max(us): 21263, 99th(us): 8703, 99.9th(us): 9879, 99.99th(us): 11575
INSERT - Takes(s): 30.0, Count: 1256845, OPS: 41901.2, Avg(us): 2165, Min(us): 425, Max(us): 21263, 99th(us): 8695, 99.9th(us): 9879, 99.99th(us): 11655
INSERT - Takes(s): 40.0, Count: 1600210, OPS: 40009.6, Avg(us): 2274, Min(us): 368, Max(us): 418815, 99th(us): 8711, 99.9th(us): 10471, 99.99th(us): 358143
INSERT - Takes(s): 50.0, Count: 1758318, OPS: 35169.6, Avg(us): 2603, Min(us): 348, Max(us): 460287, 99th(us): 8815, 99.9th(us): 251391, 99.99th(us): 407295
INSERT - Takes(s): 60.0, Count: 1916595, OPS: 31945.7, Avg(us): 2887, Min(us): 346, Max(us): 460287, 99th(us): 8967, 99.9th(us): 329471, 99.99th(us): 429055
INSERT - Takes(s): 70.0, Count: 2070688, OPS: 29583.2, Avg(us): 3131, Min(us): 346, Max(us): 763391, 99th(us): 9079, 99.9th(us): 363263, 99.99th(us): 464639
INSERT - Takes(s): 80.0, Count: 2228342, OPS: 27855.8, Avg(us): 3338, Min(us): 346, Max(us): 776703, 99th(us): 9175, 99.9th(us): 391679, 99.99th(us): 670207
INSERT - Takes(s): 90.0, Count: 2381046, OPS: 26457.1, Avg(us): 3517, Min(us): 346, Max(us): 779263, 99th(us): 9271, 99.9th(us): 415231, 99.99th(us): 684031
INSERT - Takes(s): 100.0, Count: 2540558, OPS: 25406.7, Avg(us): 3673, Min(us): 346, Max(us): 779263, 99th(us): 9367, 99.9th(us): 427007, 99.99th(us): 679935
INSERT - Takes(s): 110.0, Count: 2696446, OPS: 24514.2, Avg(us): 3813, Min(us): 346, Max(us): 779263, 99th(us): 9519, 99.9th(us): 430079, 99.99th(us): 674303
INSERT - Takes(s): 120.0, Count: 2852440, OPS: 23771.2, Avg(us): 3943, Min(us): 326, Max(us): 828415, 99th(us): 9719, 99.9th(us): 438527, 99.99th(us): 681471
INSERT - Takes(s): 130.0, Count: 3009783, OPS: 23153.0, Avg(us): 4055, Min(us): 326, Max(us): 828415, 99th(us): 10271, 99.9th(us): 439551, 99.99th(us): 678911
INSERT - Takes(s): 140.0, Count: 3166206, OPS: 22616.4, Avg(us): 4151, Min(us): 326, Max(us): 828415, 99th(us): 16383, 99.9th(us): 442623, 99.99th(us): 675327
INSERT - Takes(s): 150.0, Count: 3324504, OPS: 22164.0, Avg(us): 4243, Min(us): 326, Max(us): 828415, 99th(us): 29743, 99.9th(us): 444415, 99.99th(us): 670719
INSERT - Takes(s): 160.0, Count: 3482115, OPS: 21763.7, Avg(us): 4320, Min(us): 326, Max(us): 828415, 99th(us): 39039, 99.9th(us): 446463, 99.99th(us): 667135
INSERT - Takes(s): 170.0, Count: 3637455, OPS: 21397.4, Avg(us): 4395, Min(us): 326, Max(us): 828415, 99th(us): 43999, 99.9th(us): 451839, 99.99th(us): 668671
INSERT - Takes(s): 180.0, Count: 3790226, OPS: 21057.3, Avg(us): 4470, Min(us): 326, Max(us): 828415, 99th(us): 52735, 99.9th(us): 453887, 99.99th(us): 664575
INSERT - Takes(s): 190.0, Count: 3944269, OPS: 20759.8, Avg(us): 4540, Min(us): 326, Max(us): 828415, 99th(us): 66367, 99.9th(us): 453631, 99.99th(us): 662527
INSERT - Takes(s): 200.0, Count: 4101565, OPS: 20508.3, Avg(us): 4599, Min(us): 326, Max(us): 828415, 99th(us): 76223, 99.9th(us): 453887, 99.99th(us): 657407
INSERT - Takes(s): 210.0, Count: 4255981, OPS: 20267.0, Avg(us): 4655, Min(us): 326, Max(us): 828415, 99th(us): 82303, 99.9th(us): 453887, 99.99th(us): 654335
INSERT - Takes(s): 220.0, Count: 4406971, OPS: 20032.1, Avg(us): 4707, Min(us): 326, Max(us): 828415, 99th(us): 87615, 99.9th(us): 454911, 99.99th(us): 652287
INSERT - Takes(s): 230.0, Count: 4565209, OPS: 19849.0, Avg(us): 4756, Min(us): 326, Max(us): 828415, 99th(us): 91903, 99.9th(us): 456191, 99.99th(us): 664063
INSERT - Takes(s): 240.0, Count: 4723611, OPS: 19682.1, Avg(us): 4794, Min(us): 326, Max(us): 828415, 99th(us): 95615, 99.9th(us): 456447, 99.99th(us): 669695
INSERT - Takes(s): 250.0, Count: 4878559, OPS: 19514.5, Avg(us): 4836, Min(us): 326, Max(us): 876543, 99th(us): 98047, 99.9th(us): 457471, 99.99th(us): 691711
INSERT - Takes(s): 260.0, Count: 5034000, OPS: 19361.9, Avg(us): 4879, Min(us): 326, Max(us): 902143, 99th(us): 99839, 99.9th(us): 459775, 99.99th(us): 703999
INSERT - Takes(s): 270.0, Count: 5183762, OPS: 19199.4, Avg(us): 4917, Min(us): 326, Max(us): 902143, 99th(us): 101375, 99.9th(us): 461823, 99.99th(us): 719871
INSERT - Takes(s): 280.0, Count: 5347000, OPS: 19096.7, Avg(us): 4949, Min(us): 326, Max(us): 902143, 99th(us): 103295, 99.9th(us): 463103, 99.99th(us): 729599
INSERT - Takes(s): 290.0, Count: 5435154, OPS: 18742.2, Avg(us): 5045, Min(us): 326, Max(us): 1057791, 99th(us): 109503, 99.9th(us): 466175, 99.99th(us): 749055
INSERT - Takes(s): 300.0, Count: 5486663, OPS: 18289.2, Avg(us): 5171, Min(us): 326, Max(us): 1294335, 99th(us): 117247, 99.9th(us): 470015, 99.99th(us): 789503
INSERT - Takes(s): 310.0, Count: 5537368, OPS: 17862.7, Avg(us): 5291, Min(us): 326, Max(us): 1616895, 99th(us): 125503, 99.9th(us): 473855, 99.99th(us): 953343
INSERT - Takes(s): 320.0, Count: 5590717, OPS: 17471.2, Avg(us): 5411, Min(us): 326, Max(us): 1616895, 99th(us): 134783, 99.9th(us): 479231, 99.99th(us): 1134591
INSERT - Takes(s): 330.0, Count: 5644759, OPS: 17105.6, Avg(us): 5532, Min(us): 326, Max(us): 1762303, 99th(us): 144255, 99.9th(us): 496127, 99.99th(us): 1339391
INSERT - Takes(s): 340.0, Count: 5698785, OPS: 16761.3, Avg(us): 5649, Min(us): 326, Max(us): 1762303, 99th(us): 159871, 99.9th(us): 523775, 99.99th(us): 1340415
INSERT - Takes(s): 350.0, Count: 5751464, OPS: 16433.0, Avg(us): 5765, Min(us): 326, Max(us): 1762303, 99th(us): 173567, 99.9th(us): 555007, 99.99th(us): 1339391
INSERT - Takes(s): 360.0, Count: 5806847, OPS: 16130.3, Avg(us): 5874, Min(us): 326, Max(us): 1762303, 99th(us): 182911, 99.9th(us): 592383, 99.99th(us): 1353727
INSERT - Takes(s): 370.0, Count: 5861933, OPS: 15843.2, Avg(us): 5983, Min(us): 326, Max(us): 1762303, 99th(us): 190335, 99.9th(us): 646143, 99.99th(us): 1366015
INSERT - Takes(s): 380.0, Count: 5913587, OPS: 15562.3, Avg(us): 6090, Min(us): 326, Max(us): 1762303, 99th(us): 198655, 99.9th(us): 683519, 99.99th(us): 1366015
INSERT - Takes(s): 390.0, Count: 5967675, OPS: 15301.9, Avg(us): 6197, Min(us): 326, Max(us): 1762303, 99th(us): 204287, 99.9th(us): 719359, 99.99th(us): 1371135
INSERT - Takes(s): 400.0, Count: 6019816, OPS: 15049.7, Avg(us): 6305, Min(us): 326, Max(us): 1762303, 99th(us): 212351, 99.9th(us): 750591, 99.99th(us): 1371135
INSERT - Takes(s): 410.0, Count: 6072110, OPS: 14810.2, Avg(us): 6408, Min(us): 326, Max(us): 1762303, 99th(us): 220159, 99.9th(us): 778239, 99.99th(us): 1370111
INSERT - Takes(s): 420.0, Count: 6126077, OPS: 14586.1, Avg(us): 6509, Min(us): 326, Max(us): 1762303, 99th(us): 228095, 99.9th(us): 787967, 99.99th(us): 1369087
INSERT - Takes(s): 430.0, Count: 6178205, OPS: 14368.1, Avg(us): 6608, Min(us): 326, Max(us): 1762303, 99th(us): 235647, 99.9th(us): 803327, 99.99th(us): 1368063
INSERT - Takes(s): 440.0, Count: 6232475, OPS: 14164.9, Avg(us): 6703, Min(us): 326, Max(us): 1762303, 99th(us): 242431, 99.9th(us): 813567, 99.99th(us): 1366015
INSERT - Takes(s): 450.0, Count: 6284728, OPS: 13966.2, Avg(us): 6800, Min(us): 326, Max(us): 1762303, 99th(us): 248447, 99.9th(us): 825343, 99.99th(us): 1366015
INSERT - Takes(s): 460.0, Count: 6337398, OPS: 13777.1, Avg(us): 6895, Min(us): 326, Max(us): 1762303, 99th(us): 254847, 99.9th(us): 834047, 99.99th(us): 1364991
INSERT - Takes(s): 470.0, Count: 6392559, OPS: 13601.3, Avg(us): 6987, Min(us): 326, Max(us): 1762303, 99th(us): 262399, 99.9th(us): 842239, 99.99th(us): 1364991
INSERT - Takes(s): 480.0, Count: 6446532, OPS: 13430.4, Avg(us): 7077, Min(us): 326, Max(us): 1762303, 99th(us): 269311, 99.9th(us): 868351, 99.99th(us): 1364991
INSERT - Takes(s): 490.0, Count: 6501611, OPS: 13268.7, Avg(us): 7165, Min(us): 326, Max(us): 1762303, 99th(us): 276735, 99.9th(us): 879103, 99.99th(us): 1363967
INSERT - Takes(s): 500.0, Count: 6554826, OPS: 13109.8, Avg(us): 7252, Min(us): 326, Max(us): 1762303, 99th(us): 283135, 99.9th(us): 881151, 99.99th(us): 1363967
INSERT - Takes(s): 510.0, Count: 6608772, OPS: 12958.5, Avg(us): 7340, Min(us): 326, Max(us): 1762303, 99th(us): 289791, 99.9th(us): 879103, 99.99th(us): 1362943
INSERT - Takes(s): 520.0, Count: 6659669, OPS: 12807.2, Avg(us): 7425, Min(us): 326, Max(us): 1762303, 99th(us): 296191, 99.9th(us): 876543, 99.99th(us): 1361919
INSERT - Takes(s): 530.0, Count: 6714604, OPS: 12669.2, Avg(us): 7508, Min(us): 326, Max(us): 1762303, 99th(us): 300799, 99.9th(us): 877055, 99.99th(us): 1361919
INSERT - Takes(s): 540.0, Count: 6765542, OPS: 12528.9, Avg(us): 7591, Min(us): 326, Max(us): 1762303, 99th(us): 305151, 99.9th(us): 875519, 99.99th(us): 1360895
INSERT - Takes(s): 550.0, Count: 6818866, OPS: 12398.0, Avg(us): 7671, Min(us): 326, Max(us): 1762303, 99th(us): 308735, 99.9th(us): 879103, 99.99th(us): 1359871
INSERT - Takes(s): 560.0, Count: 6874505, OPS: 12276.0, Avg(us): 7748, Min(us): 326, Max(us): 1762303, 99th(us): 312319, 99.9th(us): 891391, 99.99th(us): 1359871
INSERT - Takes(s): 570.0, Count: 6908343, OPS: 12120.0, Avg(us): 7785, Min(us): 326, Max(us): 1762303, 99th(us): 313599, 99.9th(us): 898047, 99.99th(us): 1360895
INSERT_ERROR - Takes(s): 4.1, Count: 185, OPS: 45.1, Avg(us): 2000572, Min(us): 1999872, Max(us): 2001919, 99th(us): 2001919, 99.9th(us): 2001919, 99.99th(us): 2001919
INSERT - Takes(s): 580.0, Count: 6918610, OPS: 11928.7, Avg(us): 7775, Min(us): 326, Max(us): 1762303, 99th(us): 313087, 99.9th(us): 897535, 99.99th(us): 1360895
INSERT_ERROR - Takes(s): 14.1, Count: 664, OPS: 47.1, Avg(us): 2000643, Min(us): 1999872, Max(us): 2002943, 99th(us): 2001919, 99.9th(us): 2001919, 99.99th(us): 2002943
INSERT - Takes(s): 590.0, Count: 6929260, OPS: 11744.6, Avg(us): 7765, Min(us): 326, Max(us): 1762303, 99th(us): 312575, 99.9th(us): 897535, 99.99th(us): 1359871
INSERT_ERROR - Takes(s): 24.1, Count: 1142, OPS: 47.4, Avg(us): 2000681, Min(us): 1999872, Max(us): 2002943, 99th(us): 2001919, 99.9th(us): 2001919, 99.99th(us): 2002943
INSERT - Takes(s): 600.0, Count: 6940334, OPS: 11567.3, Avg(us): 7754, Min(us): 326, Max(us): 1762303, 99th(us): 312063, 99.9th(us): 897023, 99.99th(us): 1359871
INSERT_ERROR - Takes(s): 34.1, Count: 1618, OPS: 47.4, Avg(us): 2000696, Min(us): 1999872, Max(us): 2002943, 99th(us): 2001919, 99.9th(us): 2001919, 99.99th(us): 2002943
INSERT - Takes(s): 610.0, Count: 6951582, OPS: 11396.1, Avg(us): 7743, Min(us): 326, Max(us): 1762303, 99th(us): 311551, 99.9th(us): 896511, 99.99th(us): 1359871
INSERT_ERROR - Takes(s): 44.1, Count: 2093, OPS: 47.5, Avg(us): 2000716, Min(us): 1999872, Max(us): 2002943, 99th(us): 2001919, 99.9th(us): 2002943, 99.99th(us): 2002943
INSERT - Takes(s): 620.0, Count: 6962520, OPS: 11229.9, Avg(us): 7732, Min(us): 326, Max(us): 1762303, 99th(us): 311039, 99.9th(us): 895999, 99.99th(us): 1359871
INSERT_ERROR - Takes(s): 54.1, Count: 2568, OPS: 47.5, Avg(us): 2000728, Min(us): 1999872, Max(us): 2002943, 99th(us): 2001919, 99.9th(us): 2001919, 99.99th(us): 2002943
INSERT - Takes(s): 630.0, Count: 6973359, OPS: 11068.9, Avg(us): 7722, Min(us): 326, Max(us): 1762303, 99th(us): 310527, 99.9th(us): 895999, 99.99th(us): 1359871
INSERT_ERROR - Takes(s): 64.1, Count: 3043, OPS: 47.5, Avg(us): 2000738, Min(us): 1999872, Max(us): 2002943, 99th(us): 2001919, 99.9th(us): 2001919, 99.99th(us): 2002943`

from help ,do not know how to  change info level ?

**Comment by dbsid** [comment]
I don't think there is option to change the info level

**Comment by qiuxinyidian** [comment]
en, maybe something wong with db
