### ISSUE TITLE
foundationdb is not registered

### ISSUE THREAD

**Issue by Qingnan1** [pingcap/go-ycsb#273]
using the latest lib from "https://github.com/pingcap/go-ycsb/releases/latest" and then run command:
./go-ycsb load foundationdb -P workloads/workloada
or 
./go-ycsb load foundationdb -P workloads/workloada -p fdb.cluster=/etc/foundationdb/fdb.cluster -p fdb.dbname=DB
getting the error:
foundationdb is not registered

fdbcli --version
FoundationDB CLI 6.2 (v6.2.11)

**Comment by dbsid** [comment]
could you provide a pr to fix it?

**Comment by Qingnan1** [comment]
Find out the reason, it was because I used the released version to run the test , but the release verdion doesn't contain  foudationdb and rocksdb, need to build the project by source code. We can check more details in Makefile
