### ISSUE TITLE
load : recordcount > 10w, err is not nil, so load increament so slow

### ISSUE THREAD

**Issue by dbgosin** [pingcap/go-ycsb#37]
https://github.com/pingcap/go-ycsb/blob/2a023e57266287bf83c391ebf60cb805ac8f0ffc/pkg/workload/core.go#L264

**Comment by dbgosin** [comment]
> Error 1461: Can't create more than max_prepared_stmt_count statements (current value: 16382)

I can't make sure why this program product so many prepare statement, up to limit size

**Comment by dbgosin** [comment]
helo siddontang, I debug go-ycsb found that you cache stmt to "state.stmtCache[query] = stmt", but insert field is random, so it will make stmt up to limit size. cause golang gc && "Error 1461 Can't create more than max_prepared_stmt_count statements "

example 

> input hash -6642103758825856165 INSERT IGNORE INTO gosin (YCSB_KEY ,field5 ,field7 ,field8 ,field1 ,field2 ,field3 ,field4 ,field0 ,field6 ,field9) VALUES (? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,?)
input hash 9057049739354581371 INSERT IGNORE INTO gosin (YCSB_KEY ,field2 ,field3 ,field4 ,field9 ,field0 ,field5 ,field6 ,field7 ,field8 ,field1) VALUES (? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,?)
input hash 4067031113361928275 INSERT IGNORE INTO gosin (YCSB_KEY ,field3 ,field5 ,field7 ,field8 ,field9 ,field0 ,field2 ,field4 ,field6 ,field1) VALUES (? ,? ,? ,? ,? ,? ,? ,? ,? ,? ,?)

>

**Comment by siddontang** [comment]
Thanks @dbgosin 

I will fix it ASAP.

**Comment by siddontang** [comment]
hi @dbgosin 

can you try #39 and check whether it fixes the problem or not?
