### ISSUE TITLE
go-ycsb complaining foundationdb is not registered

### ISSUE THREAD

**Issue by emarkham** [pingcap/go-ycsb#59]
Is foundationdb actively supported?

$ ./bin/go-ycsb run foundationdb -P workloads/workloada
foundationdb is not registered

$ fdbcli --version
FoundationDB CLI 5.1 (v5.1.7)
source version 9ad8d02386d4a6a5efecf898df80f2747695c627
protocol fdb00a551040001

$ go version
go version go1.10.3 linux/amd64

**Comment by siddontang** [comment]
what is the output when you make?

**Comment by emarkham** [comment]
no make errors

$ make
go build -o bin/go-ycsb cmd/go-ycsb/*
$

**Comment by emarkham** [comment]
This is a fresh packer build of Ubuntu 16.04 using the official AMI (owner 099720109477), foundation installed using apt and a fresh install of go 1.10.3

I've tried the Makefile you suggest, still no luck. But a good clue by building manually 


$ go build -tags foundationdb -o bin/go-ycsb  cmd/go-ycsb/*
# github.com/pingcap/go-ycsb/vendor/github.com/apple/foundationdb/bindings/go/src/fdb
In file included from vendor/github.com/apple/foundationdb/bindings/go/src/fdb/cluster.go:27:0:
/usr/include/foundationdb/fdb_c.h:35:2: error: #error Requested API version requires a newer version of this header
 #error Requested API version requires a newer version of this header
  ^

$ sudo apt search foundationdb
Sorting... Done
Full Text Search... Done
foundationdb-clients/now 5.1.7-1 amd64 [installed,local]
  FoundationDB clients and library

foundationdb-server/now 5.1.7-1 amd64 [installed,local]
  FoundationDB server

vendor/github.com/apple/foundationdb/bindings/go/src/fdb/cluster.go:
23 package fdb
 24
 25 /*
 26  #define FDB_API_VERSION 520
 27  #include <foundationdb/fdb_c.h>
 28 */

/usr/include/foundationdb/fdb_c.h:
 30 #if !defined(FDB_API_VERSION)
 31 #error You must #define FDB_API_VERSION prior to including fdb_c.h (current version is 510)
 32 #elif FDB_API_VERSION < 13
 33 #error API version no longer supported (upgrade to 13)
 34 #elif FDB_API_VERSION > 510
 35 #error Requested API version requires a newer version of this header
 36 #endif

**Comment by emarkham** [comment]
confirmed that installing FoundationDB 5.2.5-1 from Apple directly solves the problem. I should have run the build directly. 

Might be a good idea to expose build errors?

**Comment by siddontang** [comment]
@emarkham 

seem that we need to upgrade to 5.2 now, can you help me file a PR?

**Comment by emarkham** [comment]
@siddontang
I  filed a PR to fix the Makefile, not sure what else to do for 5.2 support other than document it

**Comment by siddontang** [comment]
Thanks @emarkham

**Comment by dipshirajput** [comment]
Hi @emarkham ,
I have foundationDB version --- FoundationDB CLI 6.3 (v6.3.23)
but still i am getting the following error,
```

dipshi@Dipshi:~$ ./go-ycsb run foundationdb -P YCSB/workloads/workloada
Using request distribution 'zipfian' a keyrange of [0 1000]
foundationdb is not registered
```

please let me know what could be the issue ?
Thanks in advance.

**Comment by kebukeYi** [comment]
![Image](https://github.com/user-attachments/assets/7cb9982b-2d99-46b9-8d66-263273e8ba9d)

Ensure that the custom database package is correctly imported in the file cmd/go-ycsb/main.go.
